### ISSUE TITLE
Spaces! Spaces! Spaces! And "$@"

### ISSUE THREAD

**Issue by moll** [skybet/shonkwrap#1]
Hey,

``` sh
npm shrinkwrap $*
```

Always use `"$@"` to not kill args with spaces in them. ;-)

Cheers

**Comment by glenjamin** [comment]
Are there any potential shrinkwrap arts with spaces in?

Either way, I shall change this and aim to remember this in future - thanks! 😀

**Comment by glenjamin** [comment]
Fixed in `v1.1.2`

**Comment by moll** [comment]
Yay. Turns out that shrinkwrap doesn't take any arguments, but better be safe than sorry once it does. ;-)

**Comment by glenjamin** [comment]
I tend to use `shonkwrap --dev` :)

**Comment by moll** [comment]
Ah, right. Forgot that one. And the NPM manpages aren't exactly up to standard wrt to listing options.
