### ISSUE TITLE
output order is non-deterministic

### ISSUE THREAD

**Issue by tamird** [skybet/shonkwrap#4]
running shonkwrap multiple times can change the ordering of items in npm-shrinkwrap.json. It'd be nice to have deterministic ordering.

**Comment by glenjamin** [comment]
I've never noticed this - what OS are you on?

Do you have a reproducing test case?

**Comment by tamird** [comment]
I'm on OS X 10.11.1 and Node 5.0.0. Here's the file on which I observe this issue: https://github.com/cockroachdb/cockroach/blob/master/ui/npm-shrinkwrap.json

EDIT: I actually do not observe this on Node 5.0.0; I earlier saw it on Node 4.1.

**Comment by evocateur** [comment]
@tamird If you're using `npm` 2.x (which is the default in `node` 4.x), [shrinkwarp](https://www.npmjs.com/package/shrinkwarp) will provide deterministic output (alphabetized dependency keys). `node` 5.x includes `npm` 3.x, which does the sorting by default.
